### ISSUE TITLE
The bug of viewing the cni file

### ISSUE THREAD

**Issue by R2008KK** [pk5ls20/sd-webui-controlnet-fastload#11]
An error occurs when launching the webui:
```
2024-08-23 21:24:39,172 - ControlNetFastload - INFO - Load Controlnet Fastload Filter on isRemote=None and accessLevel=2
*** Error executing callback ui_tabs_callback for D:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet-fastload\scripts\fastload_view.py
    Traceback (most recent call last):
      File "D:\A1111\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet-fastload\scripts\fastload_view.py", line 60, in on_ui_tabs
        currentDir = os.path.join(scripts.basedir(), opts.data.get("outdir_txt2img_samples"))
      File "D:\Python3.10.6\lib\ntpath.py", line 143, in join
        genericpath._check_arg_types('join', path, *paths)
      File "D:\Python3.10.6\lib\genericpath.py", line 152, in _check_arg_types
        raise TypeError(f'{funcname}() argument must be str, bytes, or '
    TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

---
Running on local URL:  http://127.0.0.1:7860
```
And when I click "run" in View saved data, a notification appears "Error
Expecting value: line 1 column 1 (char 0)" and an error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
ValueError: dictionary update sequence element #0 has length 832; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 832; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]
Applying attention optimization: xformers... done.
Model loaded in 99.6s (load weights from disk: 12.6s, load config: 0.2s, create model: 2.0s, apply weights to model: 81.7s, apply channels_last: 0.2s, apply half(): 0.1s, move model to device: 0.2s, load textual inversion embeddings: 0.6s, calculate empty prompt: 1.8s).
```

### Steps to reproduce the problem / 重现问题的步骤

The problem appeared from the very download of the extension. I tried most of the instructions for the errors found, but nothing helped.

**Comment by R2008KK** [comment]
the problem was solved after reinstalling webui
